#ifndef PROTOCOL_H
#define PROTOCOL_H

// Protocol commands
#define CMD_LOGIN "LOGIN"
#define CMD_LOGOUT "LOGOUT"
#define CMD_REGISTER "REGISTER"
#define CMD_CREATE_MATCH "CREATE_MATCH"
#define CMD_JOIN_MATCH "JOIN_MATCH"
#define CMD_MOVE "MOVE"
#define CMD_SURRENDER "SURRENDER"
#define CMD_GET_MATCHES "GET_MATCHES"
#define CMD_GET_GAME_STATE "GET_GAME_STATE"
#define CMD_GET_HISTORY "GET_HISTORY"

// Timer commands
#define CMD_START_TIMER "START_TIMER"
#define CMD_STOP_TIMER "STOP_TIMER"
#define CMD_PAUSE_TIMER "PAUSE_TIMER"
#define CMD_RESUME_TIMER "RESUME_TIMER"
#define CMD_GET_TIME "GET_TIME"

// Response messages
#define RESP_OK "OK"
#define RESP_ERROR "ERROR"
#define RESP_MOVE_SUCCESS "MOVE_SUCCESS"
#define RESP_GAME_END "GAME_END"
#define RESP_OPPONENT_MOVE "OPPONENT_MOVE"
#define RESP_SURRENDER_SUCCESS "SURRENDER_SUCCESS"
#define RESP_TIMER_STARTED "TIMER_STARTED"
#define RESP_TIMER_STOPPED "TIMER_STOPPED"
#define RESP_TIMER_PAUSED "TIMER_PAUSED"
#define RESP_TIMER_RESUMED "TIMER_RESUMED"

// Protocol separators
#define CMD_SEPARATOR "|"
#define PARAM_SEPARATOR "|"

#endif
