#ifndef PROTOCOL_H
#define PROTOCOL_H

// Protocol commands
#define CMD_LOGIN "LOGIN"
#define CMD_LOGOUT "LOGOUT"
#define CMD_REGISTER "REGISTER"
#define CMD_CREATE_MATCH "CREATE_MATCH"
#define CMD_JOIN_MATCH "JOIN_MATCH"
#define CMD_MOVE "MOVE"
#define CMD_SURRENDER "SURRENDER"
#define CMD_GET_MATCHES "GET_MATCHES"
#define CMD_GET_GAME_STATE "GET_GAME_STATE"
#define CMD_GET_HISTORY "GET_HISTORY"

// Timer commands
#define CMD_START_TIMER "START_TIMER"
#define CMD_STOP_TIMER "STOP_TIMER"
#define CMD_PAUSE_TIMER "PAUSE_TIMER"
#define CMD_RESUME_TIMER "RESUME_TIMER"
#define CMD_GET_TIME "GET_TIME"

// Matchmaking commands
#define CMD_MMJOIN "MMJOIN"
#define CMD_MMSTATUS "MMSTATUS"
#define CMD_MMCANCEL "MMCANCEL"
#define RESP_MATCHED "MATCHED"
#define RESP_QUEUED "QUEUED"
#define RESP_CANCELED "CANCELED"
#define RESP_WAITING "WAITING"

// ELO commands
#define CMD_GET_ELO_HISTORY "GET_ELO_HISTORY"
#define CMD_GET_LEADERBOARD "GET_LEADERBOARD"
#define RESP_ELO_HISTORY "ELO_HISTORY"
#define RESP_LEADERBOARD "LEADERBOARD"

// Login responses
#define RESP_LOGIN_SUCCESS "LOGIN_SUCCESS"
#define RESP_REGISTER_OK "REGISTER_OK"
#define RESP_REGISTER_ERROR "REGISTER_ERROR"

// Bot commands
#define CMD_MODE_BOT "MODE_BOT"
#define CMD_BOT_MOVE "BOT_MOVE"

// Friend commands
#define CMD_FRIEND_REQUEST "FRIEND_REQUEST"
#define CMD_FRIEND_ACCEPT "FRIEND_ACCEPT"
#define CMD_FRIEND_DECLINE "FRIEND_DECLINE"
#define CMD_FRIEND_LIST "FRIEND_LIST"
#define CMD_FRIEND_REQUESTS "FRIEND_REQUESTS"

// Game control commands
#define CMD_PAUSE "PAUSE"
#define CMD_RESUME "RESUME"
#define CMD_DRAW "DRAW"
#define CMD_DRAW_ACCEPT "DRAW_ACCEPT"
#define CMD_DRAW_DECLINE "DRAW_DECLINE"
#define CMD_REMATCH "REMATCH"
#define CMD_REMATCH_ACCEPT "REMATCH_ACCEPT"
#define CMD_REMATCH_DECLINE "REMATCH_DECLINE"

// In-game chat command
#define CMD_GAME_CHAT "GAME_CHAT"
#define RESP_GAME_CHAT_FROM "GAME_CHAT_FROM"

// Response messages
#define RESP_OK "OK"
#define RESP_ERROR "ERROR"
#define RESP_MOVE_SUCCESS "MOVE_SUCCESS"
#define RESP_GAME_END "GAME_END"
#define RESP_OPPONENT_MOVE "OPPONENT_MOVE"
#define RESP_SURRENDER_SUCCESS "SURRENDER_SUCCESS"
#define RESP_TIMER_STARTED "TIMER_STARTED"
#define RESP_TIMER_STOPPED "TIMER_STOPPED"
#define RESP_TIMER_PAUSED "TIMER_PAUSED"
#define RESP_TIMER_RESUMED "TIMER_RESUMED"

// Protocol separators
#define CMD_SEPARATOR "|"
#define PARAM_SEPARATOR "|"

#endif
